application: trend-images
version: 1
runtime: python
api_version: 1

handlers:
- url: /(favicon.ico)
  static_files: static/images/favicon.ico
  upload: static/images/* 
- url: /(robots.txt)
  static_files: robots.txt
  upload: robots.txt 
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /jqueryui
  static_dir: static/jqueryui
- url: /galleria
  static_dir: static/galleria
- url: /tasks/.*
  script: app/tasks/main.py
  login: admin
- url: /.*
  script: main.py
